### ISSUE TITLE
Informational Pages

### ISSUE THREAD

**Issue by dkulp23** [dkulp23/301-Final-Project#5]
Set of questions for user reporting the OD to ensure that they want to activate the system.
Pictures or descriptions of symptoms of people who are ODing...does the person look like this?
Once user has checked off necessary boxes or confirmed symptoms they are able to click a button to activate response.

**Comment by ghost** [comment]
This will need to be cleaned up a bit with styling to fit mobile screens. Leaving in 'review' column for now.
